<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Covered_file_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get covered_file by id
     */
    function get_covered_file($id)
    {
        return $this->db->get_where('covered_files',array('id'=>$id))->row_array();
    }

    /*
     * Get all covered_files filtered by fk_test_id
     */
    function get_all_covered_files($id=null)
    {
        $this->db->order_by('id', 'desc');
        if ($id == null)
          return $this->db->get('covered_files')->result_array();
        else
          return $this->db->get_where('covered_files', array('fk_test_id'=>$id))->result_array();
    }

    /*
     * Get test name for fk_test_id
     */
    function get_test_name($id)
    {
        $this->db->select('test_name');
        return $this->db->get_where('tests',array('id'=>$id))->row()->test_name;
    }

    /*
     * function to add new covered_file
     */
    function add_covered_file($params)
    {
        $this->db->insert('covered_files',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update covered_file
     */
    function update_covered_file($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('covered_files',$params);
    }

    /*
     * function to delete covered_file
     */
    function delete_covered_file($id)
    {
        return $this->db->delete('covered_files',array('id'=>$id));
    }
}
