<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Included_file_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get included_file by id
     */
    function get_included_file($id)
    {
        return $this->db->get_where('included_files',array('id'=>$id))->row_array();
    }

    /*
     * Get all included_files filtered by fk_test_id
     */
    function get_all_included_files($id=null)
    {
        $this->db->order_by('id', 'desc');
        if ($id == null)
          return $this->db->get('included_files')->result_array();
        else
          return $this->db->get_where('included_files', array('fk_test_id'=>$id))->result_array();
    }

    /*
     * Get test name for fk_test_id
     */
    function get_test_name($id)
    {
        $this->db->select('test_name');
        return $this->db->get_where('tests',array('id'=>$id))->row()->test_name;
    }

    /*
     * function to add new included_file
     */
    function add_included_file($params)
    {
        $this->db->insert('included_files',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update included_file
     */
    function update_included_file($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('included_files',$params);
    }

    /*
     * function to delete included_file
     */
    function delete_included_file($id)
    {
        return $this->db->delete('included_files',array('id'=>$id));
    }
}
