<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Software_function_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get software_function by id
     */
    function get_software_function($id)
    {
        return $this->db->get_where('software_functions',array('id'=>$id))->row_array();
    }


    /*
     * function to add new software_function
     */
    function add_software_function($fk_software_file, $function_name, $line_number, $line_count, $removed)
    {
        $insert_data = array('fk_software_file'=>$fk_software_file, 'function_name'=>$function_name, 'line_number'=>$line_number, 'line_count'=>$line_count, 'removed'=>$removed);
        $this->db->insert('software_functions', $insert_data);
        return $this->db->insert_id();
    }

    /*
     * function to update software_function
     */
    function update_software_function($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('software_functions',$params);
    }

    /*
     * function to delete software_function
     */
    function delete_software_function($id)
    {
        return $this->db->delete('software_functions',array('id'=>$id));
    }
}
