<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Software_version_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get software_version by id
     */
    function get_software_version($id)
    {
        return (array)$this->db->get_where('software_version',array('id'=>$id))->row();
    }

    /*
     * Get all software_version
     */
    function get_all_software_version()
    {
        $this->db->select('software_version.id, software.name, software_version.version, software_version.fk_software_id')
         ->from('software_version')
         ->join('software', 'software_version.fk_software_id = software.id')
         ->order_by('id', 'desc');
        return $this->db->get()->result_array();
    }

    /*
     * function to add new software_version
     */
    function add_software_version($params)
    {
        $this->db->insert('software_version',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update software_version
     */
    function update_software_version($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('software_version',$params);
    }

    /*
     * function to delete software_version
     */
    function delete_software_version($id)
    {
        return $this->db->delete('software_version',array('id'=>$id));
    }
}
