<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Software_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get software by id
     */
    function get_software($id)
    {
        return (array)$this->db->get_where('software',array('id'=>$id))->row();
    }

    /*
     * Get all software
     */
    function get_all_software()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('software')->result_array();
    }

    /*
     * function to add new software
     */
    function add_software($params)
    {
        $this->db->insert('software',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update software
     */
    function update_software($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('software',$params);
    }

    /*
     * function to delete software
     */
    function delete_software($id)
    {
        return $this->db->delete('software',array('id'=>$id));
    }
}
