<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Test_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get test by id
     */
    function get_test($id)
    {
        return $this->db->get_where('tests',array('id'=>$id))->row_array();
    }

    /*
     * Get all tests
     */
    function get_all_tests()
    {
        $this->db->select('tests.id, tests.test_name, tests.test_group, tests.test_date, software.name, software_version.version')
         ->from('tests')
         ->join('software', 'tests.fk_software_id = software.id')
         ->join('software_version', 'tests.fk_software_version_id = software_version.id')
         ->order_by('id', 'desc');
        return $this->db->get()->result_array();
    }

    /*
     * Get all tests
     */
    function get_all_tests_by_group($id)
    {
        $this->db->select('tests.id, tests.test_name, tests.test_group, tests.test_date, software.name, software_version.version')
         ->from('tests')
         ->join('software', 'tests.fk_software_id = software.id')
         ->join('software_version', 'tests.fk_software_version_id = software_version.id')
         ->where('INSTR(tests.test_group, "'.$id.'") > 0')
         ->order_by('id', 'desc');
        return $this->db->get()->result_array();
    }

    /*
     * Get all test groups
     */
    function get_all_test_groups()
    {
      $this->db->distinct();
      $this->db->select('test_group')
       ->from('tests');
      return $this->db->get()->result_array();
    }

    /*
     * function to add new test
     */
    function add_test($params)
    {
        $this->db->insert('tests',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update test
     */
    function update_test($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tests',$params);
    }

    /*
     * function to delete test
     */
    function delete_test($id)
    {
        return $this->db->delete('tests',array('id'=>$id));
    }

    /*
     * function to delete all tests and included and covered files and lines
     */
    function delete_all_tests($id)
    {
        $this->db->truncate('covered_lines');
        $this->db->truncate('covered_files');
        $this->db->truncate('included_files');
        return $this->db->truncate('tests');
    }

    /*
     * function to delete all tests and included and covered files and lines filtered by test_group
     */
    function delete_all_tests_by_group($group_name)
    {
      return $this->db->query('
        DELETE tests, covered_files, covered_lines
        FROM tests
        JOIN covered_files ON covered_files.fk_test_id = tests.id
        JOIN covered_lines ON covered_lines.fk_file_id = covered_files.id
        WHERE tests.test_group = ?', $group_name);

        // This assumes you are using included_files table;
        // return $this->db->query('
        //   DELETE tests, covered_files, covered_lines, included_files
        //   FROM tests
        //   JOIN included_files ON included_files.fk_test_id = tests.id
        //   JOIN covered_files ON covered_files.fk_test_id = tests.id
        //   JOIN covered_lines ON covered_lines.fk_file_id = covered_files.id
        //   WHERE tests.test_group = ?', $group_name);
    }
}
