<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Vulnerable_line_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get vulnerable_line by id
     */
    function get_vulnerable_line($id)
    {
        return $this->db->get_where('vulnerable_lines',array('id'=>$id))->row_array();
    }

    /*
     * Get all vulnerable_lines
     */
    function get_all_vulnerable_lines($id=null)
    {
        $this->db->select('vulnerable_lines.id, vulnerabilities.cve, software.name, software_version.version, vulnerable_lines.line_number, fk_vulnerability_software')
         ->from('vulnerable_lines')
         ->join('vulnerability_software', 'vulnerable_lines.fk_vulnerability_software = vulnerability_software.id')
         ->join('vulnerabilities', 'vulnerability_software.fk_vulnerability_id = vulnerabilities.id')
         ->join('software_version', 'vulnerability_software.fk_version_id = software_version.id')
         ->join('software', 'software_version.fk_software_id = software.id')
         ->order_by('id', 'desc');
        if($id == null)
          return $this->db->get()->result_array();
        else
          return $this->db->get_where('', array('fk_vulnerable_file'=>$id))->result_array();
    }

    /*
     * Get file name for fk_vulnerable_file
     */
    function get_file_name($id)
    {
        $this->db->select('file_name');
        return $this->db->get_where('vulnerable_files',array('id'=>$id))->row()->file_name;
    }


    /*
     * function to add new vulnerable_line
     */
    function add_vulnerable_line($params)
    {
        $this->db->insert('vulnerable_lines',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update vulnerable_line
     */
    function update_vulnerable_line($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vulnerable_lines',$params);
    }

    /*
     * function to delete vulnerable_line
     */
    function delete_vulnerable_line($id)
    {
        return $this->db->delete('vulnerable_lines',array('id'=>$id));
    }
}
