<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Vulnerable_function_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get vulnerable_function by id
     */
    function get_vulnerable_function($id)
    {
        return $this->db->get_where('vulnerable_functions',array('id'=>$id))->row_array();
    }

    /*
     * Get all vulnerable_functions
     */
    function get_all_vulnerable_functions()
    {
        $this->db->select('vulnerable_functions.id, vulnerabilities.cve, software.name, software_version.version, vulnerable_functions.function_name, vulnerable_functions.line_number')
         ->from('vulnerable_functions')
         ->join('vulnerability_software', 'vulnerable_functions.fk_vulnerability_software = vulnerability_software.id')
         ->join('vulnerabilities', 'vulnerability_software.fk_vulnerability_id = vulnerabilities.id')
         ->join('software_version', 'vulnerability_software.fk_version_id = software_version.id')
         ->join('software', 'software_version.fk_software_id = software.id')
         ->order_by('id', 'desc');
        return $this->db->get()->result_array();
    }

    /*
     * function to add new vulnerable_function
     */
    function add_vulnerable_function($params)
    {
        $this->db->insert('vulnerable_functions',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update vulnerable_function
     */
    function update_vulnerable_function($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vulnerable_functions',$params);
    }

    /*
     * function to delete vulnerable_function
     */
    function delete_vulnerable_function($id)
    {
        return $this->db->delete('vulnerable_functions',array('id'=>$id));
    }
}
