<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Covered_file extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Covered_file_model');
    }

    /*
     * Listing of covered_files
     */
    function index($id=null)
    {
        if($id==null) {
            $data['covered_files'] = $this->Covered_file_model->get_all_covered_files();
            $data['test_name'] = null;
        }
        else
        {
            $data['covered_files'] = $this->Covered_file_model->get_all_covered_files($id);
            $data['test_name'] = $this->Covered_file_model->get_test_name($id);
        }
        $data['_view'] = 'covered_file/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new covered_file
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'fk_test_id' => $this->input->post('fk_test_id'),
				'file_name' => $this->input->post('file_name'),
            );

            $covered_file_id = $this->Covered_file_model->add_covered_file($params);
            redirect('covered_file/index');
        }
        else
        {
			$this->load->model('Test_model');
			$data['all_tests'] = $this->Test_model->get_all_tests();

            $data['_view'] = 'covered_file/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a covered_file
     */
    function edit($id)
    {
        // check if the covered_file exists before trying to edit it
        $data['covered_file'] = $this->Covered_file_model->get_covered_file($id);

        if(isset($data['covered_file']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
        					'fk_test_id' => $this->input->post('fk_test_id'),
        					'file_name' => $this->input->post('file_name'),
                );

                $this->Covered_file_model->update_covered_file($id,$params);
                redirect('covered_file/index');
            }
            else
            {
        				$this->load->model('Test_model');
        				$data['all_tests'] = $this->Test_model->get_all_tests();

                $data['_view'] = 'covered_file/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The covered_file you are trying to edit does not exist.');
    }

    /*
     * Deleting covered_file
     */
    function remove($id)
    {
        $covered_file = $this->Covered_file_model->get_covered_file($id);

        // check if the covered_file exists before trying to delete it
        if(isset($covered_file['id']))
        {
            $this->Covered_file_model->delete_covered_file($id);
            redirect('covered_file/index');
        }
        else
            show_error('The covered_file you are trying to delete does not exist.');
    }

}
