<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class included_file extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Included_file_model');
    }

    /*
     * Listing of included_files
     */
    function index($id=null)
    {
        if($id==null) {
            $data['included_files'] = $this->Included_file_model->get_all_included_files();
            $data['test_name'] = null;
        }
        else
        {
            $data['included_files'] = $this->Included_file_model->get_all_included_files($id);
            $data['test_name'] = $this->Included_file_model->get_test_name($id);
        }
        $data['_view'] = 'included_file/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new included_file
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'fk_test_id' => $this->input->post('fk_test_id'),
				'file_name' => $this->input->post('file_name'),
            );

            $included_file_id = $this->Included_file_model->add_included_file($params);
            redirect('included_file/index');
        }
        else
        {
			$this->load->model('Test_model');
			$data['all_tests'] = $this->Test_model->get_all_tests();

            $data['_view'] = 'included_file/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a included_file
     */
    function edit($id)
    {
        // check if the included_file exists before trying to edit it
        $data['included_file'] = $this->Included_file_model->get_included_file($id);

        if(isset($data['included_file']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
        					'fk_test_id' => $this->input->post('fk_test_id'),
        					'file_name' => $this->input->post('file_name'),
                );

                $this->Included_file_model->update_included_file($id,$params);
                redirect('included_file/index');
            }
            else
            {
        				$this->load->model('Test_model');
        				$data['all_tests'] = $this->Test_model->get_all_tests();

                $data['_view'] = 'included_file/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The included_file you are trying to edit does not exist.');
    }

    /*
     * Deleting included_file
     */
    function remove($id)
    {
        $included_file = $this->Included_file_model->get_included_file($id);

        // check if the included_file exists before trying to delete it
        if(isset($included_file['id']))
        {
            $this->Included_file_model->delete_included_file($id);
            redirect('included_file/index');
        }
        else
            show_error('The included_file you are trying to delete does not exist.');
    }

}
