<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Software_version extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Software_version_model');
    }

    /*
     * Listing of software_version
     */
    function index()
    {
        $data['software_version'] = $this->Software_version_model->get_all_software_version();

        $data['_view'] = 'software_version/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new software_version
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'fk_software_id' => $this->input->post('fk_software_id'),
				'version' => $this->input->post('version'),
            );

            $software_version_id = $this->Software_version_model->add_software_version($params);
            redirect('software_version/index');
        }
        else
        {
      			$this->load->model('Software_model');
      			$data['all_software'] = $this->Software_model->get_all_software();

            $data['_view'] = 'software_version/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a software_version
     */
    function edit($id)
    {
        // check if the software_version exists before trying to edit it
        $data['software_version'] = $this->Software_version_model->get_software_version($id);

        if(isset($data['software_version']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'fk_software_id' => $this->input->post('fk_software_id'),
					'version' => $this->input->post('version'),
                );

                $this->Software_version_model->update_software_version($id,$params);
                redirect('software_version/index');
            }
            else
            {
				$this->load->model('Software_model');
				$data['all_software'] = $this->Software_model->get_all_software();

                $data['_view'] = 'software_version/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The software_version you are trying to edit does not exist.');
    }

    /*
     * Deleting software_version
     */
    function remove($id)
    {
        $software_version = $this->Software_version_model->get_software_version($id);

        // check if the software_version exists before trying to delete it
        if(isset($software_version['id']))
        {
            $this->Software_version_model->delete_software_version($id);
            redirect('software_version/index');
        }
        else
            show_error('The software_version you are trying to delete does not exist.');
    }

}
