<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Vulnerable_file extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vulnerable_file_model');
    }

    /*
     * Listing of vulnerable_files
     */
    function index()
    {
        $data['vulnerable_files'] = $this->Vulnerable_file_model->get_all_vulnerable_files();

        $data['_view'] = 'vulnerable_file/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vulnerable_file
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
      				'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
      				'file_name' => $this->input->post('file_name'),
            );

            $vulnerable_file_id = $this->Vulnerable_file_model->add_vulnerable_file($params);
            redirect('vulnerable_file/index');
        }
        else
        {
      			$this->load->model('Vulnerability_software_model');
      			$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

            $data['_view'] = 'vulnerable_file/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a vulnerable_file
     */
    function edit($id)
    {
        // check if the vulnerable_file exists before trying to edit it
        $data['vulnerable_file'] = $this->Vulnerable_file_model->get_vulnerable_file($id);

        if(isset($data['vulnerable_file']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
        					'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
        					'file_name' => $this->input->post('file_name'),
                );

                $this->Vulnerable_file_model->update_vulnerable_file($id,$params);
                redirect('vulnerable_file/index');
            }
            else
            {
        				$this->load->model('Vulnerability_software_model');
        				$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

                $data['_view'] = 'vulnerable_file/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vulnerable_file you are trying to edit does not exist.');
    }

    /*
     * Deleting vulnerable_file
     */
    function remove($id)
    {
        $vulnerable_file = $this->Vulnerable_file_model->get_vulnerable_file($id);

        // check if the vulnerable_file exists before trying to delete it
        if(isset($vulnerable_file['id']))
        {
            $this->Vulnerable_file_model->delete_vulnerable_file($id);
            redirect('vulnerable_file/index');
        }
        else
            show_error('The vulnerable_file you are trying to delete does not exist.');
    }

}
