<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Vulnerable_line extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vulnerable_line_model');
    }

    /*
     * Listing of vulnerable_lines
     */
    function index($id=null)
    {
        if($id==null) {
          $data['vulnerable_lines'] = $this->Vulnerable_line_model->get_all_vulnerable_lines();
          $data['file_name'] = null;
        }
        else
        {
          $data['vulnerable_lines'] = $this->Vulnerable_line_model->get_all_vulnerable_lines($id);
          $data['file_name'] = $this->Vulnerable_line_model->get_file_name($id);
        }
        $data['_view'] = 'vulnerable_line/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vulnerable_line
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
				'fk_vulnerable_file' => $this->input->post('fk_vulnerable_file'),
				'line_number' => $this->input->post('line_number'),
            );

            $vulnerable_line_id = $this->Vulnerable_line_model->add_vulnerable_line($params);
            redirect('vulnerable_line/index');
        }
        else
        {
			$this->load->model('Vulnerability_software_model');
			$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

			$this->load->model('Vulnerable_file_model');
			$data['all_vulnerable_files'] = $this->Vulnerable_file_model->get_all_vulnerable_files();

            $data['_view'] = 'vulnerable_line/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a vulnerable_line
     */
    function edit($id)
    {
        // check if the vulnerable_line exists before trying to edit it
        $data['vulnerable_line'] = $this->Vulnerable_line_model->get_vulnerable_line($id);

        if(isset($data['vulnerable_line']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
					'fk_vulnerable_file' => $this->input->post('fk_vulnerable_file'),
					'line_number' => $this->input->post('line_number'),
                );

                $this->Vulnerable_line_model->update_vulnerable_line($id,$params);
                redirect('vulnerable_line/index');
            }
            else
            {
				$this->load->model('Vulnerability_software_model');
				$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

				$this->load->model('Vulnerable_file_model');
				$data['all_vulnerable_files'] = $this->Vulnerable_file_model->get_all_vulnerable_files();

                $data['_view'] = 'vulnerable_line/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vulnerable_line you are trying to edit does not exist.');
    }

    /*
     * Deleting vulnerable_line
     */
    function remove($id)
    {
        $vulnerable_line = $this->Vulnerable_line_model->get_vulnerable_line($id);

        // check if the vulnerable_line exists before trying to delete it
        if(isset($vulnerable_line['id']))
        {
            $this->Vulnerable_line_model->delete_vulnerable_line($id);
            redirect('vulnerable_line/index');
        }
        else
            show_error('The vulnerable_line you are trying to delete does not exist.');
    }

}
