<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Vulnerable_function extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vulnerable_function_model');
    }

    /*
     * Listing of vulnerable_functions
     */
    function index()
    {
        $data['vulnerable_functions'] = $this->Vulnerable_function_model->get_all_vulnerable_functions();

        $data['_view'] = 'vulnerable_function/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vulnerable_function
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
      				'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
      				'fk_vulnerable_file' => $this->input->post('fk_vulnerable_file'),
      				'line_number' => $this->input->post('line_number'),
              'function_name' => $this->input->post('function_name'),
            );

            $vulnerable_function_id = $this->Vulnerable_function_model->add_vulnerable_function($params);
            redirect('vulnerable_function/index');
        }
        else
        {
      			$this->load->model('Vulnerability_software_model');
      			$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

      			$this->load->model('Vulnerable_file_model');
      			$data['all_vulnerable_files'] = $this->Vulnerable_file_model->get_all_vulnerable_files();

            $data['_view'] = 'vulnerable_function/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a vulnerable_function
     */
    function edit($id)
    {
        // check if the vulnerable_function exists before trying to edit it
        $data['vulnerable_function'] = $this->Vulnerable_function_model->get_vulnerable_function($id);

        if(isset($data['vulnerable_function']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'fk_vulnerability_software' => $this->input->post('fk_vulnerability_software'),
					'fk_vulnerable_file' => $this->input->post('fk_vulnerable_file'),
					'line_number' => $this->input->post('line_number'),
          'function_name' => $this->input->post('function_name'),
                );

                $this->Vulnerable_function_model->update_vulnerable_function($id,$params);
                redirect('vulnerable_function/index');
            }
            else
            {
				$this->load->model('Vulnerability_software_model');
				$data['all_vulnerability_software'] = $this->Vulnerability_software_model->get_all_vulnerability_software();

				$this->load->model('Vulnerable_file_model');
				$data['all_vulnerable_files'] = $this->Vulnerable_file_model->get_all_vulnerable_files();

                $data['_view'] = 'vulnerable_function/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vulnerable_function you are trying to edit does not exist.');
    }

    /*
     * Deleting vulnerable_function
     */
    function remove($id)
    {
        $vulnerable_function = $this->Vulnerable_function_model->get_vulnerable_function($id);

        // check if the vulnerable_function exists before trying to delete it
        if(isset($vulnerable_function['id']))
        {
            $this->Vulnerable_function_model->delete_vulnerable_function($id);
            redirect('vulnerable_function/index');
        }
        else
            show_error('The vulnerable_function you are trying to delete does not exist.');
    }

}
